### ISSUE TITLE
inputTraj = IInputData.create("HDFTrajectoryInputData", self["value"]) KeyError: 'value'

### ISSUE THREAD

**Issue by DawnHNguyen** [ISISNeutronMuon/MDANSE-Examples#10] opened 2024-08-12 14:40 UTC
Hi, I'm new to MDANSE. I'm running your example project. After I cloned your project, setup virtual env for python using `python3 -m venv mdanse` and `source mdanse/bin/activate`, also install `mdanse` and `mdanse_gui` through pip. I'm able to launch mdanse_gui, but when I'm trying to run `script_4.py`, there is an error
```
mdanse_env/lib/python3.10/site-packages/MDANSE/Framework/Configurators/HDFTrajectoryConfigurator.py", line 52, in configure
    inputTraj = IInputData.create("HDFTrajectoryInputData", self["value"])
KeyError: 'value'
```
How can I fix that, does this mean my env setup has something wrong or am I missing some step.
Thank you so much

**Comment by ChiCheng45** [comment] 2024-08-12 15:17
Hi,

I think this issue should be sorted when we merge #9. I'm just waiting for someone to review and merge the change. Basically, we made some changes to the code and the scripts haven't been updated yet. 

If you are familiar with git you should be able to check out the tutorial1-script-fixes branch and try running those scripts again. Alternatively, you can edit the scripts manually to get it working, see https://github.com/ISISNeutronMuon/MDANSE-Examples/pull/9/files.

**Comment by DawnHNguyen** [comment] 2024-08-12 15:53
Hi @ChiCheng45, thank you for answering me. Unfortunately, after checkout to `tutorial1-script-fixes`, I still can't run the scrip4. It still the same error. And also the script1, too. Does that mean it have an issue in my env setup. I'm using `MDANSE==2.0.0a2` 
and `MDANSE_GUI==0.1.0a3` (as using pip3 freeze), python 3.10.12

**Comment by DawnHNguyen** [comment] 2024-08-19 01:49
Hi @ChiCheng45. How is it going? Has anyone approve your PR yet

**Comment by MBartkowiakSTFC** [comment] 2024-08-21 09:56
Hi @DawnHNguyen, I have been away. Apologies for the delay. The PR has been reviewed and merged now.

Please let me know if everything worked for you. Did scripts 1-3 work for you, and the problem is only limited to script 4?

**Comment by MBartkowiakSTFC** [comment] 2024-08-21 10:14
@DawnHNguyen 
Overall, the error message you were getting indicates that the input trajectory could not be found. This should be independent of the code changes discussed above. The main reasons could be:
1. The working directory of the script was wrong (since the scripts use relative paths), or
2. `script1_conversion.py` was never run. (It's the one which creates the input trajectory for the other scripts)

So, please make sure that you are starting the scripts from `tutorial1-phase-transition/mdanse-inputs`, so they can find the LAMMPS trajectory files in `../md_inputs/` and `../md_outputs/`, and later the converted trajectory in `../mdanse_outputs/`.

**Comment by DawnHNguyen** [comment] 2024-08-21 10:23
@MBartkowiakSTFC maybe because I'm start running script 4 first that make the problem. Tonight after comeback home, I will try again, start running from script 1 then 2, 3, 4 and will update later. Many thanks

**Comment by DawnHNguyen** [comment] 2024-08-21 13:41
Hi @MBartkowiakSTFC. After pull main and run script 1 using `python3 tutorials/tutorial1-phase-transition/mdanse_inputs/script1_conversion.py`, there is an error 
`MDANSE-Examples/mdanse_env/lib/python3.10/site-packages/MDANSE/Framework/Jobs/IJob.py", line 164, in initialize
    and self.configuration["output_files"]["write_logs"]
KeyError: 'write_logs'`. Could you please help me with that

**Comment by MBartkowiakSTFC** [comment] 2024-08-21 14:01
Hi @DawnHNguyen , could you show me the `parameters` dictionary from that script? Specifically, line 19 has 'output_files'. For me it looks like this:
`    'output_files': ('../mdanse_outputs/converted_trajectory', 32, 'gzip', "INFO"),  # MDANSE trajectory (filename, format)
`

I can reproduce your error if I change "INFO" to something invalid. But when I use the original version of the script, everything works.

**Comment by DawnHNguyen** [comment] 2024-08-21 14:08
I'm currently pull main and run, I does not change anything. This is the `script1_conversion.py`
```
#!/usr/bin/env python

########################################################
# This is an automatically generated MDANSE run script #
########################################################

from MDANSE.Framework.Jobs.IJob import IJob

########################################################
# Job parameters                                       #
########################################################

parameters = {
    'atom_aliases': '{"mass=96.0": {"1": "Mo"}}',       # Atom mapping
    'config_file': '../md_inputs/structure.txt',  # LAMMPS configuration file
    'fold': False,                                      # Fold coordinates in to box
    'lammps_units': 'electron',                         # LAMMPS unit system
    'n_steps': '0',                                     # Number of time steps (0 for automatic detection)
    'output_files': ('../mdanse_outputs/converted_trajectory', 32, 'gzip', "INFO"),  # MDANSE trajectory (filename, format)
    'time_step': '0.2',                                 # Time step (lammps units, depends on unit system)
    'trajectory_file': '../md_outputs/trajectory.txt',  # LAMMPS trajectory file
    'trajectory_format': 'custom',                      # LAMMPS trajectory format
}

########################################################
# Setup and run the analysis                           #
########################################################

if __name__ == "__main__":
    lammps = IJob.create('LAMMPS')
    lammps.run(parameters, status=True)
```

**Comment by MBartkowiakSTFC** [comment] 2024-08-21 15:36
Could you just do:
`cd tutorials/tutorial1-phase-transition/mdanse_inputs`
`python script1_conversion.py`
and see if it works? You are welcome to consult README.md (lines 69-74) of the tutorial regarding this part.

**Comment by DawnHNguyen** [comment] 2024-08-22 03:26
Oh yeah, now I understand what you say at. the working directory (as said in README) must be `mdanse-inputs` and not the top level git package. Thank you so much
> So, please make sure that you are starting the scripts from `tutorial1-phase-transition/mdanse-inputs`, so they can find the LAMMPS trajectory files in `../md_inputs/` and `../md_outputs/`, and later the converted trajectory in `../mdanse_outputs/`.

**Comment by MBartkowiakSTFC** [comment] 2024-08-22 08:07
Are things working for you now? Please let me know if this issue can be closed now.

Based on this situation, I have created an issue that we will follow up to improve the way the scripts are run: https://github.com/ISISNeutronMuon/MDANSE-Examples/issues/11

**Comment by DawnHNguyen** [comment] 2024-08-22 09:08
Thank for your help, I can run the script1 fine, nothing wrong with it. But after run script2, script3, script4, it return `Decode failed for inputs: <HDF5 group "/metadata/inputs" (9 members)>`. But I think I don't have to care about it, do I? Because I'm currently not install mdanse_gui, just install mdanse to check that the script can run probably. Again, thank you so much for your kind support

**Comment by MBartkowiakSTFC** [comment] 2024-08-22 09:10
You are right, that `Decode failed ...` message is not really important.

Happy to hear that the scripts work now.

**Closed by MBartkowiakSTFC** 2024-08-22 09:10 UTC
